src/app/[roomId]/editor-text-area.tsx
src/app/[roomId]/styles.css
src/components/copy.tsx
src/lib/stores/yjs-store.tsx
src/lib/utils.ts
tsconfig.json

- **Initial render for username tags**
- **Cursor usernames are working!**
- **Improve remote cursor design**

Add username tags to remote cursors

---

apps/web/providers/code-room-provider.tsx

fix(rooms): user in empty room not notified when the next user joins

---

apps/web/app/(room)/[slug]/layout.tsx
apps/web/app/_components/create-room-button.tsx
apps/web/app/layout.tsx
apps/web/components/command-menu/command-menu.tsx
apps/web/components/command-menu/commands/interface-theme.tsx
apps/web/components/editor/editor-text-area.tsx
apps/web/components/editor/editor-toolbar.tsx
apps/web/components/editor/editor-users-list.tsx
apps/web/components/editor/themes.ts
apps/web/package.json
apps/web/providers/index.tsx
apps/web/providers/theme-provider.tsx
packages/ui/src/components/ui/combobox.tsx
packages/ui/src/components/ui/command.tsx
packages/ui/src/components/ui/dropdown-menu.tsx
packages/ui/src/globals.css
packages/ui/tailwind.config.ts
pnpm-lock.yaml

- **Add next-themes**
- **Add theme provider to global providers**
- **Add command to change interface themes to menu**
- **Cleanup unused code**
- **Dark mode popover bg**
- **More cleanup**
- **Updates**
- **Updates**
- **Feature flag for themes access**

feat: dark mode

---

apps/web/app/(auth)/login/buttons.tsx
apps/web/app/(auth)/login/page.tsx
apps/web/components/editor/copy-room-url.tsx
apps/web/components/editor/editor-users-list.tsx
apps/web/components/editor/my-account-dropdown.tsx
packages/ui/src/components/ui/button.tsx

- **Expose collision padding tooltip API on button**
- **Add/use new tooltip button wrapper for standalone buttons**
- **Add tooltips for login methods**

feat: add tooltips for standalone buttons

---

apps/web/components/editor/editor-toolbar.tsx
apps/web/components/editor/editor-users-list.tsx
apps/web/components/editor/room-title.tsx
apps/web/package.json
apps/web/providers/code-room-provider.tsx
packages/database/src/schema.ts
packages/ui/src/components/ui/input.tsx
pnpm-lock.yaml

- **Working!**
- **Fix dark mode styles for active users list overflow count**

feat: set code room title

---

.prototools
apps/api/Dockerfile

- **Bump Bun version in prototools**
- **Bump Bun version for API container**

chore(deps): bump Bun to v1.1.43

---

.github/workflows/release.yaml
apps/api/Dockerfile
apps/api/src/routes/rooms.ts
apps/sync/Dockerfile
apps/web/Dockerfile
package.json
packages/database/src/drizzle.ts
turbo.json

- **Export `ne` (not equal) Drizzle operator**
- **Write editor language to database upon change event**
- **Squash merge main into avelin-128-sync-changes-to-database-via-webhook**

feat(rooms): sync editor language changes to database via webhook

---

apps/api/src/routes/rooms.ts
apps/api/src/utils/auth.utils.ts
packages/database/migrations/0010_composite-pk-room-participants.sql
packages/database/migrations/meta/0010_snapshot.json
packages/database/migrations/meta/_journal.json
packages/database/src/schema.ts
packages/id/src/generate.ts

- **Drop `id` column and references, add composite primary key, create migration**
- **Update account linking logic**

chore(db): use composite primary key for room participants

---

.github/workflows/release.yaml
packages/database/migrations/0010_composite-pk-room-participants.sql

- **Add statement breakpoint**
- **Fix naming for workflow titles**

fix(db): migration has missing statement breakpoint

---

.github/workflows/release.yaml
apps/web/components/editor/room-title.tsx

- **X**
- **Fix uncontrolled to controlled input error**
- **Fix migration CI step**

fix: room title input changes from uncontrolled to controlled

---

.github/workflows/build-ubi-images.yaml
packages/ubi/README.md
packages/ubi/bun-node/Dockerfile
packages/ubi/bun/Dockerfile
packages/ubi/node/Dockerfile
packages/ubi/package.json

- **Checkpoint**
- **Remove scripts**

ci: build ubi images for distribution

---

apps/web/app/layout.tsx
apps/web/components/misc/one-dollar-stats.tsx
apps/web/lib/env.ts

- **Add one dollar stats, NODE_ENV var**
- **Load script on client to use event handlers**

chore: one dollar stats

---

apps/web/app/(auth)/login/page.tsx
apps/web/app/dashboard/_components/toolbar.tsx
apps/web/app/dashboard/_components/v1/empty-rooms.tsx
apps/web/app/dashboard/_components/v1/rooms-list.network.tsx
apps/web/app/dashboard/_components/v1/rooms-list.tsx
apps/web/app/dashboard/_components/v1/rooms-list.zero.tsx
apps/web/app/dashboard/layout.tsx
apps/web/app/dashboard/page.tsx
apps/web/app/globals.css
apps/web/app/layout.tsx
apps/web/components/devtools/toolbar.tsx
apps/web/components/devtools/zero-cache.tsx
apps/web/hooks/use-resize-observer.tsx
apps/web/lib/mutations.zero.ts
apps/web/providers/index.tsx

- **Remove other disabled signin options**
- **Progress**
- **more changes**
- **Done**
- **Cleanup**

feat(dashboard): continued overhaul

---

.github/workflows/release.yaml
apps/api/package.json
apps/api/src/index.ts
apps/api/src/routes/auth.ts
pnpm-lock.yaml

feat: disable anonymous sessions

---

apps/web/app/(landing)/layout.tsx
apps/web/app/(landing)/page.tsx

- **Fixed mobile view**
- **Remove red border debugging**

feat: waitlist landing - mobile view

---

apps/api/src/env.ts
apps/api/src/routes/auth.ts
apps/web/app/(app)/dashboard/_components/v1/rooms-list.zero.tsx
apps/web/app/(app)/dashboard/_components/v1/user-avatar-list.tsx
apps/web/app/(app)/dashboard/layout.tsx
apps/web/app/(landing)/layout.tsx
apps/web/components/editor/editor-toolbar.tsx
apps/web/lib/env.ts
apps/web/lib/queries.ts
apps/web/providers/auth-provider.tsx
apps/web/providers/index.tsx

feat(auth): allow anonymous access to existing code rooms

---

apps/api/src/utils/jwt.utils.ts
apps/web/lib/zero.ts
apps/web/providers/zero-provider.tsx
packages/zero/src/schema.ts
pnpm-lock.yaml
pnpm-workspace.yaml

- **Rename AuthJWT to AuthData**
- **Upgrade Zero to v0.16**
- **TypeScript niceties**

chore: upgrade @rocicorp/zero to v0.16

---

apps/api/src/routes/rooms.ts
apps/web/app/(app)/dashboard/_components/rooms-list.tsx
apps/web/app/(app)/rooms/[slug]/page.tsx
packages/zero/src/schema.ts

feat(api): update hocuspocus connect and disconnect webhooks to use room_connections table
feat(zero): update permissions for room connections table
feat(dashboard): use room connections to determine active users
perf(dashboard): preload rooms

feat(api): update hocuspocus connect and disconnect webhooks to use room_connections table

---

apps/web/app/(app)/layout.tsx
apps/web/app/(app)/rooms/[slug]/_components/code-room-deleted.tsx
apps/web/app/(app)/rooms/[slug]/page.tsx
apps/web/app/(landing)/layout.tsx
apps/web/app/globals.css
apps/web/components/command-menu/command-menu.tsx
apps/web/components/command-menu/commands/room-delete.tsx
apps/web/lib/fonts.ts
apps/web/lib/mutations.zero.ts
apps/web/providers/code-room-provider.tsx
apps/web/tailwind.config.ts
packages/zero/src/schema.ts

delete room for cmd menu
chore(fonts): use next.js font for inter
fix(zero): users can update their own room connection rows, room creator can delete room connections
feat(rooms): gracefully delete rooms

feat(rooms): delete current room from command menu

---

apps/web/app/(app)/(admin)/admin/_/waitlist-entries-table.tsx

fix(admin): use state for row pagination in waitlist table
prevent reset of page index

fix(admin): use state for row pagination in waitlist table
